### PR TITLE
Add JWT authentication doc

### PR DESCRIPTION
**Pull request by owensdj**

### CODE REVIEW

**Comment by wstrange** [comment]
Is there any way of adding the JWT claims extracted by the server interceptor to downstream consumers?

**Review by bettdouglas — APPROVED** [review]
Hello @owensdj thanks for the contribution. and sorry for taking some time to approve this. 

I was really hoping you could include the packages you're using for jwt verification so that readers could easily follow along with the provided example code. 

I'm going to merge this since anyway since it's a quick guide. Feel free to include the package you're using to validate the jwt. 
:-)

**Comment by owensdj** [comment]
@bettdouglas thanks for the merge. I mentioned in the article that I used the jaguar_jwt package for JWT verification if that's what you meant?

**Comment by bettdouglas** [comment]
Okay. It seems I wasn't keen enough. Thanks.

**Pull request merged**
